SET(LibUSB_DIR "C:/libusb-1.0.22")



SET(LibUSB_INCLUDE_DIRS ${LibUSB_DIR}/include)
SET(LibUSB_INCLUDES     ${LibUSB_DIR}/include)
SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".dll")
IF(MSVC OR ${CMAKE_GENERATOR} MATCHES "Xcode")
  SET(LibUSB_LIBRARY_DIR  ${LibUSB_DIR}/MS32/dll)  # 32bits
ELSE ()
  SET(LibUSB_LIBRARY_DIR  ${LibUSB_DIR}/MinGW32/dll)  # 32bits
ENDIF ()
FIND_LIBRARY(LibUSB_LIBS
  NAMES usb-1.0 libusb usb libusb-1.0
  PATHS ${LibUSB_LIBRARY_DIR}
  NO_DEFAULT_PATH
  NO_CMAKE_ENVIRONMENT_PATH
  NO_CMAKE_PATH
  NO_SYSTEM_ENVIRONMENT_PATH
  NO_CMAKE_SYSTEM_PATH
  )
